name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/ai-career-companion:latest infra/.

      - name: Push to Google Container Registry
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - run: |
          docker push gcr.io/$PROJECT_ID/ai-career-companion:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ai-career-companion
          image: gcr.io/$PROJECT_ID/ai-career-companion:latest
          region: us-central1
